"""empty message

Revision ID: 7f49afa35576
Revises: 
Create Date: 2024-05-03 02:50:52.787330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f49afa35576'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publishers')
    op.drop_table('admins')
    op.drop_table('authors')
    op.drop_table('members')
    op.drop_table('books')
    op.drop_table('book_reviews')
    op.drop_table('users')
    op.drop_table('issued_books')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issued_books',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date_issued', sa.DATETIME(), nullable=True),
    sa.Column('book', sa.INTEGER(), nullable=True),
    sa.Column('memmber', sa.INTEGER(), nullable=True),
    sa.Column('return_date', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['book'], ['books.book_id'], ),
    sa.ForeignKeyConstraint(['memmber'], ['members.member_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=30), nullable=False),
    sa.Column('password', sa.VARCHAR(length=30), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('verified', sa.BOOLEAN(), nullable=True),
    sa.Column('profile', sa.INTEGER(), nullable=True),
    sa.Column('is_blocked', sa.BOOLEAN(), nullable=True),
    sa.Column('role', sa.VARCHAR(), nullable=True),
    sa.Column('profile_picture', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['profile'], ['members.member_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('book_reviews',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('book_id', sa.INTEGER(), nullable=True),
    sa.Column('review', sa.VARCHAR(), nullable=True),
    sa.Column('member_id', sa.INTEGER(), nullable=True),
    sa.Column('date_created', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('books',
    sa.Column('book_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('publisher', sa.INTEGER(), nullable=True),
    sa.Column('published_date', sa.DATETIME(), nullable=True),
    sa.Column('date_created', sa.DATETIME(), nullable=True),
    sa.Column('category', sa.VARCHAR(), nullable=True),
    sa.Column('isbn', sa.VARCHAR(), nullable=True),
    sa.Column('author', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['authors.author_id'], ),
    sa.ForeignKeyConstraint(['publisher'], ['publishers.publisher_id'], ),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_table('members',
    sa.Column('member_id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(), nullable=True),
    sa.Column('last_name', sa.VARCHAR(), nullable=True),
    sa.Column('date_of_birth', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('member_id')
    )
    op.create_table('authors',
    sa.Column('author_id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(), nullable=True),
    sa.Column('last_name', sa.VARCHAR(), nullable=True),
    sa.Column('date_of_birth', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('author_id')
    )
    op.create_table('admins',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=30), nullable=False),
    sa.Column('password', sa.VARCHAR(length=30), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('profile_picture', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('publishers',
    sa.Column('publisher_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('publisher_id')
    )
    # ### end Alembic commands ###
